# Generated by Django 6.0.1 on 2026-01-13 09:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('sks', models.PositiveIntegerField(default=3)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('persentase', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nilai', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('sudah_selesai', models.BooleanField(default=False)),
                ('notifikasi_email', models.BooleanField(default=False)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semua_komponen', to='grade_tracker.matakuliah')),
            ],
        ),
    ]
