# Generated by Django 6.0.1 on 2026-01-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penilaian',
            new_name='KomponenPenilaian',
        ),
    ]
